### ISSUE TITLE
[FEATURE] Action name depending on variable

### ISSUE THREAD

**Issue by HeisenbergK** [ExperienceLovelace/ha-floorplan#454]
**Is your feature request related to a problem? Please describe.**
I want to be able to execute different actions (e.g. `homeassistant.toggle` or `navigate`) depending on the state of e.g. a sensor or a homeassistant helper integer.

**Describe the solution you'd like**
Maybe there is a solution with `floorplan.execute`?

**Describe alternatives you've considered**
Running a function in the action step where the returned string is the action name.

**Illustrations, examples, additional context**
Maybe there is a solution here: https://community.home-assistant.io/t/action-from-function/763677/3

**Comment by exetico** [comment]
I did make the first "debug"-take on this, a week ago. But it was primary to see that could be done, without making much changes. I think I need to start over, and see what's the most easy way of doing this. The thing I find a bit difficult, is to retain the svg reference and rule, after we've converted the YAML to executable JavaScript. That's not a standard operation, and requires us to split up each statement, and doing a eval-execution.

I'll get back at some point, hopefully. My next step will be to see how other developers have integrated plugin-specific "local" events for their frontend integration. If there's no restrictions regarding "custom events" send by a lovelave front-end integration, I guess a simple event handler could make more sense, instead of trying to over-complicate, by "trying and hold on to the SVG element reference and rule", in the anonymous execution of the parsed code.

_I'm putting this answer here, if another user picks up the feature requests, and end's up starting their own branch (and eventually making a PR to our repo) 😄._

**Comment by exetico** [comment]
Hi

Check the latest pre-release here:
https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.45-beta.1

Let me know what you think.

Also check:
https://experiencelovelace.github.io/ha-floorplan/docs/usage/#using-execute-with-action

It's a pre-release so you'll need to enable that in HACS, or download the dist file manually.
